-- CreateTable users
CREATE TABLE IF NOT EXISTS users (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable gifts
CREATE TABLE IF NOT EXISTS gifts (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  "imageUrl" TEXT,
  available BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable reservas
CREATE TABLE IF NOT EXISTS reservas (
  id TEXT NOT NULL PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "giftId" TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'reservado',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY ("giftId") REFERENCES gifts(id) ON DELETE CASCADE
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reservas_userId_idx" ON reservas("userId");
